config/routes.rb
Fitness::Application.routes.draw do

  post 'workouts/:id/edit' => 'workouts#update'

resources :workouts
	get 'authentications/new' => 'authentications#new'
	post 'authentications' => 'authentications#create'
	get 'authentications/:id' => 'authentications#show'
	delete 'authentications' => 'authentications#destroy'
	put 'authentications/:id' => 'authentications#update'

  get 'users' => 'users#index'
  get 'users/new' => 'users#new' #add new users
  get 'users/:id' => 'users#show'
  post 'users' => 'users#create'
  delete 'users/:id/edit' => 'users#edit'

  post 'users' => 'users#create'
  delete 'users/:id' => 'users#destroy'
  put 'users/:id' => 'users#update'

  # get 'workouts' => 'workouts#index'
  # get 'workouts/new' => 'workouts#new' #shows form to add new workout day
  # get 'workouts/:id' => 'workouts#show'


  # get 'workouts/:id/edit' => 'workouts#edit'

  # post 'workouts' => 'workouts#create' #creating new workout for admin
  # delete 'workouts/:id' => 'workouts#destroy' #editing for custom workouts
  # get 'workouts/:id/edit' => 'workouts#edit'
  #post 'workouts/:id/edit' => 'workouts#update'

end

app/models/score.rb
class Score
include Mongoid::Document

field :test_name, type:String
field :test_score, type:Float

belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User
	include Mongoid::Document

	attr_accessor :password, :password_confirmation

	field :email, type: String
	field :salt, type: String
	field :hashed_password, type: String


	has_many :scores
	before_save :hash_password
	validates :email, presence: true
	validates :email, uniqueness: { case_sensitive: false }
	validates :password, confirmation: true

def authenticate(password)
	self.hashed_password ==
	BCrypt::Engine.hash_secret(password, self.salt)
end

private
def hash_password
	if password.present?
		self.salt = BCrypt::Engine.generate_salt
		self.hashed_password =
		BCrypt::Engine.hash_secret(password, self.salt)
		password = password_confirmation = nil
	end
end
end

app/models/workout.rb
class Workout
	include Mongoid::Document

	field :name, type: String
	field :repetitions, type: Integer	
	field :sets, type: Integer


# before_save :hashed_password
# validates :email, presence: true
# validates :email, uniqueness: { case_sensitive: false }
# validates :password, confirmation: true

# def authenticate(password)
# 	self.hashed_password ==
# 	BCrypt::Engine.hash_secret(password, self.salt)
# end

# private
# def hash_password
# 	if password.present?
# 		self.salt = BCrypt::Engine.generate_salt
# 		self.hashed_password =
# 		BCrypt::Engine.hash_secret(password, self.salt)
# 		password = password_confirmation = nil
# 	end
# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    begin
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Mongoid::Errors::DocumentNotFound
    nil
    end
end

def authenticate_user
	redirect_to authentications_url unless current_user
	end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	

	def new
	# this is a login form
	if current_user 
		redirect_to workouts_url
	else 
		@user = User.new
	end
end

	def show
		@user = User.find(params[:id])
		end

	def create
		user = User.find_by(email: params[:user][:email])
	    if user != nil
	        # authenticate user
	        if user.authenticate(params[:user][:password])
	          session[:user_id] = user.id
	          redirect_to workouts_url
	        else
	          flash.now.alert = "Unable to sign you in. Please try again."
	          render :new
	        end
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to authentications_new_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def new
		@user = User.new
end

	def show
		@user = User.find(params[:id])
	end

	def create
	 @user = User.create(params[:user]
			.permit(:email, :password, :password_confirmation))
	 @user.save
		# redirect_to action: "new"
		redirect_to workouts_url
	end

	def destroy
		Users.find(params[:id]).destroy
		redirect_to authentications_new_path
	end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	
	def index
		@workouts = Workout.all
	end

	def new
		@workout = Workout.new
	end

	def show
		@workout = Workout.find(params[:id])
	end

	def create
		@workout = Workout.new(params[:workout].permit(:name, :repetitions, :sets))
		@workout.save
		redirect_to workouts_path
	end

	def edit
		@workout = Workout.find(params[:id])

	end

	def update
		@workout = Workout.find(params[:id])
		if @workout.update_attributes(params[:workout].permit(:name, :repetitions, :sets))
			redirect_to @workout
		else 
			render "edit"
		end
	end

	def destroy
		Workout.find(params[:id]).destroy
		redirect_to workouts_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentications/destroy.html.erb
<%= session[:user_id] %>

app/views/authentications/new.html.erb
<h1>Login form</h1>

<br /> 
  <%= form_for @user,{url:"/authentications", method:"post"} do |u| %>
  <br>
    <%= u.label :email, "Email" %><%=u.text_field :email %><br />
    <%= u.label :password, "Password" %><%=u.text_field :password %><br />

    <%= u.submit :Login %><br />

    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fitness</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if current_user %>
<%= button_to "Log out", authentications_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign up form</h1>

<br /> 
  <%= form_for @user do |u| %>
  <br>
    <%= u.label :email, "Email" %><%=u.text_field :email %><br />
    <%= u.label :password, "Password" %><%=u.text_field :password %><br />
    <%= u.label :password_confirmation, "Confirm" %><%=u.text_field :password_confirmation %><br />
    <%= u.submit %><br />

    <% end %>

app/views/users/show.html.erb
<%= @users.email %>
<%= @users.password_confirmation %>

app/views/workouts/edit.html.erb
<h1>Edit Exercise</h1>

<%= form_for :workout do |work|%>
<p>
		<%= work.label :name%>
		<%= work.text_field :name %>
</p>

<p>
		<%= work.label :repetitions, "Repetitions"%>
		<%= work.text_field :repetitions %>
</p>

<p>
		<%= work.label :sets, "Sets"%>
		<%= work.text_field :sets %>
</p>

<p>
	<%= work.submit :Change %>
</p>



<%end%>

app/views/workouts/index.html.erb
<%= session[:user_id] %>
<h1>Monday day 1</h1>
<h2>Strength Training Workout I</h2>

<table>
    <tr>
      <th>Excercise</th>
      <th>Repetitions</th>
      <th>Sets</th>
      <th></th>
    </tr>
 
      <td><% @workouts.each do |workout| %></td>
    <tr>
      <td><%= workout.name %></td>
      <td><%= workout.repetitions %></td>
      <td><%= workout.sets %></td>
      <td><%= button_to "delete", { action: "destroy", id: workout.id},
      {method: :delete, data:{confirm: "Are you sure?"}}%></td>
      <td><%= link_to "edit", edit_workout_path(workout) %></td>
      <br>
    </tr>
    <% end %>
</table>

app/views/workouts/new.html.erb
<h1>Change Workouts</h1>

<%= form_for @workout do |work|%>
<p>
		<%= work.label :name%>
		<%= work.text_field :name %>
</p>

<p>
		<%= work.label :repetitions, "Repeptitions"%>
		<%= work.text_field :repetitions %>
</p>

<p>
		<%= work.label :sets, "Sets"%>
		<%= work.text_field :sets %>
</p>

<p>
<%= work.submit%>
</p>

<%end%>

app/views/workouts/show.html.erb
<%= @workout.name %>
<%= @workout.repetitions %>
<%= @workout.sets %>
<%= link_to "Workout", workouts_path(@workout) %>
<%# link_to "edit", edit_workout_path(@workout) %>

app/views/workouts/users_show.erb
<%= @users.email %>
<%= @users.password_confirmation %>